// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/08ed4e9f1869e37e29514d862e0158b40e550232/react/react-global.d.ts
import React = __React;
import ReactDOM = __React.__DOM;

declare namespace __React {
    export import addons = __React.__Addons;
}
