// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/08ed4e9f1869e37e29514d862e0158b40e550232/react/react-addons-pure-render-mixin.d.ts
declare namespace __React {
    interface PureRenderMixin extends Mixin<any, any> {}

    namespace __Addons {
        export var PureRenderMixin: PureRenderMixin;
    }
}

declare module "react-addons-pure-render-mixin" {
    var PureRenderMixin: __React.PureRenderMixin;
    type PureRenderMixin = __React.PureRenderMixin;
    export = PureRenderMixin;
}
