// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/08ed4e9f1869e37e29514d862e0158b40e550232/react/react-addons-create-fragment.d.ts
declare namespace __React {
    namespace __Addons {
        export function createFragment(object: { [key: string]: ReactNode }): ReactFragment;
    }
}

declare module "react-addons-create-fragment" {
    export = __React.__Addons.createFragment;
}
